version: '3.8'

services:
  saas-api:
    image: bjsoftware/saas-api:latest
    networks:
      - network_db
      - network_public
    environment:
      - DATABASE_URL=postgresql://saas_control:Saas%231256c0ntrol@postgres:5432/saas-sistema?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=redis://redis:6379
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      # NO SWARM, AS LABELS DEVEM FICAR AQUI DENTRO DO DEPLOY
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.saas-api.rule=Host(`api.sistema.bjsoft.com.br`)"
        - "traefik.http.services.saas-api.loadbalancer.server.port=3000"
        - "traefik.docker.network=network_public"

  saas-web:
    image: bjsoftware/saas-web:latest
    networks:
      - network_public
    deploy:
      replicas: 1
      # REPETIMOS O PADRÃO AQUI
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.saas-web.rule=Host(`sistema.bjsoft.com.br`) || HostRegexp(`{subdomain:[a-z0-9]+}.sistema.bjsoft.com.br`)"
        - "traefik.http.services.saas-web.loadbalancer.server.port=80"
        - "traefik.docker.network=network_public"

networks:
  network_db:
    external: true
  network_public:
    external: true
