import { PoComboOption } from '@po-ui/ng-components';

// Subconjunto curado do catalogo Animalia Icons (an an-*) do PO-UI v21+,
// adequado para representar grupos de modulo no menu lateral.
export const MODULE_ICON_OPTIONS: PoComboOption[] = [
  { label: 'Casa', value: 'an an-house' },
  { label: 'Predios / Empresa', value: 'an an-buildings' },
  { label: 'Pasta', value: 'an an-folders' },
  { label: 'Pasta simples', value: 'an an-folder' },
  { label: 'Usuario', value: 'an an-user' },
  { label: 'Usuarios', value: 'an an-users' },
  { label: 'Usuario circular', value: 'an an-user-circle' },
  { label: 'Cartao de identificacao', value: 'an an-identification-card' },
  { label: 'Calendario', value: 'an an-calendar-blank' },
  { label: 'Calendario com eventos', value: 'an an-calendar-dots' },
  { label: 'Calendario check', value: 'an an-calendar-check' },
  { label: 'Relogio', value: 'an an-clock' },
  { label: 'Lista', value: 'an an-list-dashes' },
  { label: 'Lista com marcadores', value: 'an an-list-bullets' },
  { label: 'Lista com checks', value: 'an an-list-checks' },
  { label: 'Documento', value: 'an an-file-text' },
  { label: 'Grade / Modulos', value: 'an an-squares-four' },
  { label: 'Configuracoes', value: 'an an-gear-six' },
  { label: 'Parametros', value: 'an an-sliders-horizontal' },
  { label: 'Estrutura em arvore', value: 'an an-tree-structure' },
  { label: 'Sidebar', value: 'an an-sidebar-simple' },
  { label: 'Mapa / Localizacao', value: 'an an-map-pin' },
  { label: 'Mapa dobrado', value: 'an an-map-trifold' },
  { label: 'Globo / Mundo', value: 'an an-globe-simple' },
  { label: 'Caixa de correio', value: 'an an-mailbox' },
  { label: 'Financeiro', value: 'an an-currency-dollar-simple' },
  { label: 'Recibo', value: 'an an-receipt' },
  { label: 'Cartao de credito', value: 'an an-credit-card' },
  { label: 'Negociacao', value: 'an an-handshake' },
  { label: 'Carrinho de compras', value: 'an an-shopping-cart' },
  { label: 'Pacote / Caixa', value: 'an an-package' },
  { label: 'Grafico de barras', value: 'an an-chart-bar' },
  { label: 'Sino / Notificacao', value: 'an an-bell' },
  { label: 'Envelope', value: 'an an-envelope-simple' },
  { label: 'Telefone', value: 'an an-phone' },
  { label: 'Estrela', value: 'an an-star' },
  { label: 'Cadeado', value: 'an an-lock' },
  { label: 'Etiqueta', value: 'an an-tag' },
  { label: 'Terminal', value: 'an an-terminal-window' },
];
