import { Test, TestingModule } from '@nestjs/testing';
import { UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import * as bcrypt from 'bcrypt';
import { AuthService } from './auth.service';
import { PrismaService } from '../prisma/prisma.service';

describe('AuthService', () => {
  let service: AuthService;
  let prisma: { user: { findFirst: jest.Mock }, menu: { findMany: jest.Mock } };

  beforeEach(async () => {
    prisma = {
      user: {
        findFirst: jest.fn(),
      },
      menu: {
        findMany: jest.fn(),
      },
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        AuthService,
        { provide: PrismaService, useValue: prisma },
        { provide: JwtService, useValue: { sign: jest.fn().mockReturnValue('token') } },
      ],
    }).compile();

    service = module.get(AuthService);
  });

  it('accepts bcrypt password generated by seed', async () => {
    prisma.user.findFirst.mockResolvedValue({
      id: 1,
      tenantId: 1,
      profileId: 1,
      email: 'admin@fallback.com',
      password: await bcrypt.hash('admin123', 4),
      isActive: true,
      tenant: { id: 1, name: 'Default Tenant' },
      profile: { name: 'Administrador', profileModules: [] },
    });

    await expect(
      service.validateUser({ email: 'admin@fallback.com', password: 'admin123' }),
    ).resolves.toMatchObject({ email: 'admin@fallback.com' });
  });

  it('rejects invalid password', async () => {
    prisma.user.findFirst.mockResolvedValue({
      id: 1,
      tenantId: 1,
      profileId: 1,
      email: 'admin@fallback.com',
      password: await bcrypt.hash('admin123', 4),
      isActive: true,
      tenant: { id: 1, name: 'Default Tenant' },
      profile: { name: 'Administrador', profileModules: [] },
    });

    await expect(
      service.validateUser({ email: 'admin@fallback.com', password: 'errada' }),
    ).rejects.toBeInstanceOf(UnauthorizedException);
  });

  it('returns menu tree based on registered menus for allowed modules', async () => {
    prisma.menu.findMany.mockResolvedValue([
      { id: 10, parentId: null, label: 'Configuracoes', shortLabel: 'CFG', icon: 'an an-gear', link: null },
      { id: 11, parentId: 10, label: 'Usuarios', shortLabel: 'USR', icon: 'an an-users-three', link: '/configuracoes/usuarios' },
    ]);

    const result = await service.login({
      id: 1,
      tenantId: 1,
      profileId: 1,
      email: 'admin@fallback.com',
      name: 'Admin',
      tenant: { id: 1, name: 'Default Tenant' },
      profile: {
        id: 1,
        name: 'Administrador',
        profileModules: [{ canRead: true, module: { key: 'settings' } }],
      },
    } as any);

    expect(prisma.menu.findMany).toHaveBeenCalled();
    expect(result.user.menus).toEqual([
      {
        label: 'Configuracoes',
        shortLabel: 'CFG',
        icon: 'an an-gear',
        subItems: [
          {
            label: 'Usuarios',
            shortLabel: 'USR',
            icon: 'an an-users-three',
            link: '/configuracoes/usuarios',
          },
        ],
      },
    ]);
  });
});
